id: I20B71FC3
legacy_id: P004202
ocr_import_info:
  bdrc_scan_id: W8LS18336
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T08:44:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:08:02.753401+00:00'
last_modified: 2022-09-04 12:08:16.788998
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS18336
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS18336
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་འཛིན།
  author: ཁ་དྲོན་ནང་པ་བློ་བཟང་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.5929942601482494
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I8LS18338:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS18338
      total_pages: 452
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS18338.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5929942601482494
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
